apiVersion: v2 # Versi贸n de HELM
name: elastic
description: Chart para desplegar ElasticSearch con Kibana

type: application

version: 0.1.0   # Versi贸n del Chart
appVersion: "7.11.0"    # Versi贸n de la aplciaci贸n que voy a instalar a traves de este Chart (ELASTICSEARCH)

# Parametros informativos
# Dependencias