                # Tipo de objeto
kind:           Deployment
                # Libreria dentro de Kubernetes que contiene
                # la definición de ese tipo de objeto
apiVersion:     apps/v1


metadata:
{{ with .Release }}
                # Este es su identificador
    name:       {{ .Name }}-kibana
                # Etiquetas, con un determinado valor.
                # Qué etiquetas? Las que quiera.
    namespace: {{ .Namespace }}         
    labels:
                app: {{ .Name }}-kibana 
spec:
    replicas: {{ $.Values.kibana.replicas }}

    selector:   
        matchLabels:
            app: {{ .Name }}-kibana    # <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

    template:
        metadata:
                        # Este es su identificador
            name:       {{ .Name }}-kibana-pod 
                        # Etiquetas, con un determinado valor.
                        # Qué etiquetas? Las que quiera.
            labels:
                        app: {{ .Name }}-kibana     # <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
{{ end }}

        spec:
            containers:
                -   # Contenedor kibana
                    name:   kibana
                    image:  {{ .Values.kibana.image }}:{{ $.Chart.AppVersion }}
                    env:
                        - name: SERVER_NAME
                          valueFrom: 
                            fieldRef:
                                fieldPath: metadata.name
                        - name: SERVER_HOST
                          value: 0.0.0.0
                        - name: ELASTICSEARCH_HOSTS
                          value: http://es-coordinator-svc:9200 # TODO
                    ports:
                        - containerPort: {{ .Values.kibana.service.port }}  
                    
                    {{- if or .Values.kibana.requests.memory .Values.kibana.requests.cpu }}
                    resources:
                        requests:
                        {{- if .Values.kibana.requests.memory }}
                            memory:  {{ .Values.kibana.requests.memory }}   
                        {{- end }}
                        {{- if .Values.kibana.requests.cpu }}
                            cpu: {{ .Values.kibana.requests.cpu }}    
                        {{- end }}
                    {{- end }}
                    
                    