
kind: Service
apiVersion: v1

metadata:
    name: {{ .Release.Name }}-kibana-svc
    namespace: {{ .Release.Namespace }}         

spec:
    type: {{ .Values.kibana.service.type }} 
    selector:
        app: kibana
    ports:
        - port: {{ .Values.kibana.service.port }}
          targetPort: {{ .Values.kibana.service.port }}
          {{ if eq .Values.kibana.service.type "NodePort" }}
          nodePort: {{ .Values.kibana.service.nodePort }}
          {{ end }}


