
kind: Service
apiVersion: v1

metadata:
    name: kibana-svc

spec:
    type: {{ .Values.kibana.service.type }} 
    selector:
        app: kibana
    ports:
        - port: 5601
          targetPort: 5601
          {{ if eq .Values.kibana.service.type "NodePort" }}
          nodePort: {{ .Values.kibana.service.nodePort }}
          {{ end }}
