
kind: Service
apiVersion: v1

metadata:
    name: kibana-svc

spec:
    type: NodePort 
    selector:
        app: kibana
    ports:
        - port: 5601
          targetPort: 5601
          nodePort: 31000
          
---
                # Tipo de objeto
kind:           Deployment
                # Libreria dentro de Kubernetes que contiene
                # la definición de ese tipo de objeto
apiVersion:     apps/v1


metadata:
                # Este es su identificador
    name:       kibana
                # Etiquetas, con un determinado valor.
                # Qué etiquetas? Las que quiera.
    labels:
                app: kibana 
spec:
    replicas: 1
    
    selector:   
        matchLabels:
            app: kibana    # <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

    template:
        metadata:
                        # Este es su identificador
            name:       kibana-pod 
                        # Etiquetas, con un determinado valor.
                        # Qué etiquetas? Las que quiera.
            labels:
                        app: kibana     # <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
        spec:
            containers:
                -   # Contenedor nginx
                    name:   kibana
                    image:  docker.elastic.co/kibana/kibana:7.11.0
                    env:
                        - name: SERVER_NAME
                          valueFrom: 
                            fieldRef:
                                fieldPath: metadata.name
                        - name: SERVER_HOST
                          value: 0.0.0.0
                        - name: ELASTICSEARCH_HOSTS
                          value: http://es-coordinator-svc:9200
                    ports:
                        - containerPort: 5601   